version: '3.7'
services:
  licensingservice:
    image: licensing-service:latest
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CLOUD_CONFIG_URI:http://configserver:8071"
    networks:
      backend:
        aliases:
          - "licenseservice"
networks:
  backend:
    driver: bridge